function getChatList() {
  return [
    [1, "CSS Grid Layout Basics"],
    [2, "JavaScript Event Bubbling"],
    [3, "Responsive Navbar Design"],
    [4, "API Rate Limiting Explained"],
    [5, "Dark Mode Implementation"],
    [6, "Flexbox vs Grid Comparison"],
    [7, "Building a To-Do App"],
    [8, "Web Accessibility Basics"],
    [9, "Authentication with JWT"],
    [10, "Optimizing Website Performance"],
    [11, "Understanding Async/Await"],
    [12, "Image Optimization Techniques"],
    [13, "State Management in React"],
    [14, "Form Validation Strategies"],
    [15, "Deploying a Web App"],
    [16, "SEO Best Practices"],
  ];
}

function getChatConversation(id) {
  const chats = {
    1: [
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      {
        prompt: "qn",
        sqlQuery: "sql",
        result: [
          {
            Id: "111de5d7-a341-4862-bb95-df6aaf6b6742",
            UserName: "stuart2",
            NormalizedUserName: "STUART2",
            Email: "stuart2",
            NormalizedEmail: "STUART2",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEGgk/HhOCm19jXhhjAiKnEeHU068cjOznRbxd80C67yy0HBDuE7Tk7wjp8VJVQ2cRQ==",
            SecurityStamp: "F6DCFQG6BT2PHV5S4JISKNZOW5ZN6KLK",
            ConcurrencyStamp: "8596e349-2db9-47a5-a992-3299e4962376",
            PhoneNumber: "9090909090",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "5fa41588-aa14-41cc-8714-5030b0685b36",
            UserName: "smith",
            NormalizedUserName: "SMITH",
            Email: "smith",
            NormalizedEmail: "SMITH",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEHDIIOCiEwJ9c4ADa/0cE1CsKQw3XurjOtY3Vtdsbg2ADvtJlYFvwX0RgzgrgtMkmQ==",
            SecurityStamp: "F4BM45FCGEMX4MCPK6HCOHLGUR2SANFV",
            ConcurrencyStamp: "e2551d38-1cf4-47fd-9b11-136ed6e12c57",
            PhoneNumber: "9843580345",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "6f515eab-62f6-4097-b9b8-a7085805fb63",
            UserName: "maria",
            NormalizedUserName: "MARIA",
            Email: "maria",
            NormalizedEmail: "MARIA",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEBSPfw1wHAcRq3ajtWJIYBYGfOwcjaE+2sTHB1Yatp7o0OoVoI+czfDD+fn89lutXw==",
            SecurityStamp: "QKOLM7IPNX7V5WD5OZLUVYWUQAOBDDB2",
            ConcurrencyStamp: "26b86e22-a085-4e0a-8f0a-bc5f93373da8",
            PhoneNumber: "1231232312",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "790f1d89-27b2-4dff-8493-84496f77c6fb",
            UserName: "susie",
            NormalizedUserName: "SUSIE",
            Email: "susie",
            NormalizedEmail: "SUSIE",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEKJOjL58bP3rUXoVZE2ITFprlBVSn9vfQtOuUdhbTihu2m3J09Dh6K43bY63pVQaAA==",
            SecurityStamp: "ZRAXDNU4MGEGD4DT7FYZFLSR6TXNSCVK",
            ConcurrencyStamp: "2869c6e2-a9df-4184-840f-3eaaa1c517f0",
            PhoneNumber: "1231232375",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "80271a45-2131-4849-9d6f-13a51b083460",
            UserName: "kevin",
            NormalizedUserName: "KEVIN",
            Email: "kevin",
            NormalizedEmail: "KEVIN",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEEdF8PXhDMiRHk1Fc/n7SVXJlqAUghshjcecZ1zPM/LtweoWGN3JdSSFNOd5wyzFbQ==",
            SecurityStamp: "7JGT4HPVOL37PP7GK6HGCNB3AXDPEFWX",
            ConcurrencyStamp: "b0d0a65a-8434-4265-a8d0-bd8da6c8a98d",
            PhoneNumber: "1234123412",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "85423e76-b053-42af-97db-d7f6743e39d4",
            UserName: "stuart",
            NormalizedUserName: "STUART",
            Email: "stuart",
            NormalizedEmail: "STUART",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEAK/hIc9E9+eFjaIIhD891lIGRfjuyw7jg8cf6RxRSugsBeFkQhoDNEZ6hsmINFDng==",
            SecurityStamp: "P6FUCNDPCKCGD7H325K55FZQJTCKOHN5",
            ConcurrencyStamp: "73ff445e-0f18-4904-a983-2a7ec5df840d",
            PhoneNumber: "9090909090",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "9840d45b-7beb-4e65-a0bd-0ae59f498c93",
            UserName: "stuart3",
            NormalizedUserName: "STUART3",
            Email: "stuart3",
            NormalizedEmail: "STUART3",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEKQyS42MXNBIGIE3b1xq97A98u9WhrlYjbHJMrKn48N95/GSs28thDsZJs8JAGO79w==",
            SecurityStamp: "6GXSOO42S5U5FJYR3DTVVHFWCWRVADJC",
            ConcurrencyStamp: "99cf8b16-190a-4aec-a9aa-68bee2d62ce8",
            PhoneNumber: "9090909090",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "9fe0c1aa-6789-4e13-a881-780c841ab5c1",
            UserName: "kathir",
            NormalizedUserName: "KATHIR",
            Email: "kathir",
            NormalizedEmail: "KATHIR",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEF3fPlaGw8v9U3Hu9W9mW8W6sxUTvfH0w0QiSLYu4gHmzl1faQCHzz/Sm9gPv591OA==",
            SecurityStamp: "SQAVD7DKGLDQYIBM54ULNUPD2IM6R4Z4",
            ConcurrencyStamp: "cb655ac1-c5ea-4ede-afec-66ea91a39bd4",
            PhoneNumber: null,
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "b7d7f0be-bb1a-4b0f-a9d9-0a0c0cb52928",
            UserName: "theproudlinuxer",
            NormalizedUserName: "THEPROUDLINUXER",
            Email: "theproudlinuxer",
            NormalizedEmail: "THEPROUDLINUXER",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEKT4SB5v3XHPM7lxZ9slsLeCe0ORRSaGZRBV5Ib9brprv9S5IwUOQlGp5ZYlXysOdw==",
            SecurityStamp: "JJUAPYRU2YK2BUBI2RN2SJHAUE5OKZWB",
            ConcurrencyStamp: "94143bce-b7e4-4b52-92b8-1d0fea0435a9",
            PhoneNumber: null,
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "c43b0483-bcbe-42e2-8e7e-80dc981b9c29",
            UserName: "justin",
            NormalizedUserName: "JUSTIN",
            Email: "justin",
            NormalizedEmail: "JUSTIN",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEMC/Nsoqyst1a+PE4ftOYaga5+d1HPuqHDflL+Gie5pqnVE4Xz2tVkPiPExZrsUcZw==",
            SecurityStamp: "PSH2FSM6RNBHIVVMZCSNCQUBD53XOTOR",
            ConcurrencyStamp: "55b2289a-6d1d-4348-be57-22e4727bf85b",
            PhoneNumber: "3240723478",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "c846138c-86de-4059-b572-7513052a864f",
            UserName: "monish",
            NormalizedUserName: "MONISH",
            Email: "monish",
            NormalizedEmail: "MONISH",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEJp7PltnY4dCncn+yDqge8BBNqfhM0Vnk6mppxEBhxDDJ+qXnSXHuLs86H8Af6jo7w==",
            SecurityStamp: "FMTP5EAYUJSOA2RRECG7ZFOPSKRCLDGT",
            ConcurrencyStamp: "bee88b83-39a9-451b-b937-0d6ce9ae6d8c",
            PhoneNumber: "1234567890",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "cab4008f-df86-49e6-8325-6a9a0dd09554",
            UserName: "frank",
            NormalizedUserName: "FRANK",
            Email: "frank",
            NormalizedEmail: "FRANK",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAECRAh9WJoGVExi4nRXRD7b+R/de1jFnqV6Ha7NTGOMhy05BFXHWnT5kXRPUWes4j8Q==",
            SecurityStamp: "MMU5QZIJC4MPFHXIZXWB4IX75GLUZA7S",
            ConcurrencyStamp: "b0b9faae-995d-44d7-b99e-b523af749a40",
            PhoneNumber: "1231231233",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "d87c366b-d745-4b7a-b8f5-03d7505b843b",
            UserName: "annie",
            NormalizedUserName: "ANNIE",
            Email: "annie",
            NormalizedEmail: "ANNIE",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEN81Wzt2sMM1OxFfwouF4rftJfCrOMKszf2so+pleWLmEJUZf0WD89i5Ew3GQ87sjA==",
            SecurityStamp: "YL7KWUEPTHSBDG6KVQROLDWXFXRN2J7D",
            ConcurrencyStamp: "3b9bf888-d0b0-4e85-b3aa-c215441eb6d3",
            PhoneNumber: "1231231234",
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
          {
            Id: "fe57b9ec-ae7f-42fe-8646-20762fb8fccd",
            UserName: "bobSundareswaran",
            NormalizedUserName: "BOBSUNDARESWARAN",
            Email: "bob",
            NormalizedEmail: "BOB",
            EmailConfirmed: false,
            PasswordHash: "AQAAAAIAAYagAAAAEM4R3hTIL3gxhLejBafa2vaxS6P4hJqQs9qILfQh7gQYsfri+A7/SlRx+xxy7mJlcw==",
            SecurityStamp: "2WMZ4X3ORZT2CMWCJZZ47I25VSYXGFNB",
            ConcurrencyStamp: "93459558-b1fc-4c6b-a7be-4e012f5d6999",
            PhoneNumber: null,
            PhoneNumberConfirmed: false,
            TwoFactorEnabled: false,
            LockoutEnd: null,
            LockoutEnabled: true,
            AccessFailedCount: 0,
          },
        ],
      },
    ],
    2: [
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
    ],
    3: [
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
    ],
    4: [
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
    ],
    5: [
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
    ],
    6: [
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
      { prompt: "qn", sqlQuery: "sql", result: [] },
    ],
  };
  return chats[id];
}

export { getChatList, getChatConversation };
