from typing import Any, Dict, List, Optional, Protocol

class ChatCachePort(Protocol):
    def add_chat_block(self, user_id: str, chat_id: str, message: Any) -> None: ...

    def get_chat_history(self, user_id: str, chat_id: str) -> Optional[List[Dict[str, Any]]]: ...

    def get_all_chats(self, user_id: str) -> List[Dict[str, str]]: ...

    def create_chat(self, user_id: str, chat_id: str, chat_name: str) -> Dict[str, str]: ...

    def delete_chat(self, user_id: str, chat_id: str) -> bool: ...

    def get_chat_metadata(self, user_id: str, chat_id: str) -> str: ...

    def save_conn_id(self, user_id: str, chat_id: str, conn_id: str) -> bool: ...

    def get_conn_id(self, user_id: str, chat_id: str) -> Optional[str]: ...
